# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2d7481a1dc3e30be00e3444c2ed5faa89cc9a0cdf90a11a8aa844f955743e8581b7f2712091093312e13213375271c617b1b115bc83b780ec7413c42b3d243c

test:
  secret_key_base: ba9ebc759144f8d047671ff7b8e8bc6a63e0122472ba6d9234f5460983b80e6c8617ea2462cf36e62c550e986851a86f0e0599d871e4844ccd5e8fc479861797

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
